import Head from 'next/head'
import Image from 'next/image'
import styles from '@/styles/Home.module.css'
import React from "react";
// どうも pages 配下に styled-components ファイルを置くと npm run build でエラーになってしまう
// 別ファイルにする場合は styles/pages 配下に置く
import {
  Main,
  Title,
} from '@/styles/pages/index.style'
// import の仕方は { Main } のようにしたい
// import * as S from './index.style';
import { Header } from '@/components/Header/Header';
// indexeddb のインスタンス
import { db } from '@/db/db';
import { nanoid } from "nanoid";
import { Button } from "primereact/button";
import { ability, Can } from "@/context/permission.context";

const Home: React.FC = () => {
  const handlePermissionClick = async (subject: string = "user") => {
    await db.test.clear();
    await db.test.add({
      // id: nanoid(5),
      id: "1",
      name: new Date().toISOString(),
    });
    // ability.update([{ action: "manage", subject: subject }]);
  };

  const bulkUpdate = async (subject: string = "user") => {
    await db.test.bulkAdd([
      {
        id: "1",
        name: new Date().toISOString(),
      },
      {
        id: "2",
        name: new Date().toISOString(),
      },
      {
        id: "3",
        name: new Date().toISOString(),
      },
    ]);
  };

  return (
    <div className={styles.container}>
      <Header
        asChild={false}
        title={'React Next Docker Title Attribute'}
        className={'text-2xl'}
      >
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Header>

      <Main>
        <Title>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </Title>

        <div>
          <div>indexeddb の検証</div>
          <Button onClick={() => handlePermissionClick("user")}>Userの1件更新</Button>
          <div>User テーブルにレコードを1件作成する</div>
          <div>この User ボタンを押した瞬間に indexeddb の初期化が走る</div>

          <div>indexeddb bulk update の検証</div>
          <Button onClick={() => bulkUpdate("user")}>Userの複数件更新</Button>
          <div>すでに key が table に存在する場合はエラーになる</div>
        </div>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.tsx</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </Main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home;
